# Generated by Django 3.0 on 2022-02-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220207_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
